# Generated by Django 4.2.1 on 2023-05-23 20:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0018_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=48,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(8)],
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(8)],
                        verbose_name="Текст",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="Дата и время начала"),
                ),
                (
                    "end_time",
                    models.DateTimeField(verbose_name="Дата и время окончания"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events",
                        to="users.department",
                        verbose_name="Отдел(ы)",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="participated_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудники",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=128,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(8)],
                        verbose_name="Текст",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="events.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["-created"],
            },
        ),
    ]
