# Generated by Django 4.2.1 on 2023-05-29 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                to="users.department",
                verbose_name="Отдел(ы)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="participated_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудники",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="events.category",
                verbose_name="Категория",
            ),
        ),
    ]
