# Generated by Django 4.2.1 on 2023-05-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default="", max_length=32, unique=True, verbose_name="Слаг"
            ),
            preserve_default=False,
        ),
    ]
