# Generated by Django 4.2.1 on 2023-05-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="preview_image",
            field=models.ImageField(
                default="", upload_to="entries/", verbose_name="Превью записи"
            ),
            preserve_default=False,
        ),
    ]
