# Generated by Django 4.2.1 on 2023-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="to_all",
            field=models.BooleanField(
                default=False,
                help_text="При положительном значении, поля с сотрудниками и отделами игнорируются и приглашения отправляются всем активным сотрудникам",
                verbose_name="Отправка для всех",
            ),
        ),
    ]
