# Generated by Django 4.2.3 on 2023-07-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
    ]
