# Generated by Django 4.2.1 on 2023-05-24 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_entry_preview_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="text",
            field=models.TextField(
                max_length=128,
                validators=[django.core.validators.MinLengthValidator(8)],
                verbose_name="Текст",
            ),
        ),
    ]
