# Generated by Django 4.2.1 on 2023-05-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_entry_created_alter_event_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='eventresponse',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='eventresponse',
            name='event',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventResponse',
        ),
    ]
