# Generated by Django 4.2.1 on 2023-05-29 15:29

import datetime

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название опроса')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание опроса')),
                ('frequency', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='периодичность прохождения опроса')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время создания опроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='статус активности')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор опроса')),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SurveyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='департамент')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.survey', verbose_name='опрос')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='department',
            field=models.ManyToManyField(through='metrics.SurveyDepartment', to='users.department', verbose_name='отдел'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='текст вопроса')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='metrics.survey', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Bad', 'Плохо'), ('So so', 'Так себе'), ('OK', 'Нормально'), ('Fine', 'Хорошо'), ('Good', 'Отлично')], max_length=9, verbose_name='Настроение')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время добавления показателей')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Состояние (сотрудника)',
                'verbose_name_plural': 'Состояния',
            },
        ),
        migrations.CreateModel(
            name='CompletedSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, choices=[('Низкий уровень', 'Low'), ('Средний уровень', 'Medium'), ('Высокий уровень', 'High'), ('Критический уровень', 'Critical')], verbose_name='интерпретация результата')),
                ('positive_value', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='кол-во утвердительных ответов')),
                ('negative_value', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='кол-во отрицательных ответов')),
                ('completion_date', models.DateField(default=datetime.date.today, verbose_name='дата прохождения опроса')),
                ('next_attempt_date', models.DateField(default=datetime.date.today, verbose_name='дата следующей попытки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.survey', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'результат опроса сотрудника',
                'verbose_name_plural': 'результаты опросов сотрудников',
                'ordering': ('-id',),
            },
        ),
    ]
