# Generated by Django 4.2.1 on 2023-05-30 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("metrics", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="surveydepartment",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.department",
                verbose_name="департамент",
            ),
        ),
        migrations.AddField(
            model_name="surveydepartment",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="metrics.survey",
                verbose_name="опрос",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор опроса",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="department",
            field=models.ManyToManyField(
                through="metrics.SurveyDepartment",
                to="users.department",
                verbose_name="отдел",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="metrics.survey",
                verbose_name="опрос",
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AddField(
            model_name="completedsurvey",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="сотрудник",
            ),
        ),
        migrations.AddField(
            model_name="completedsurvey",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="metrics.survey",
                verbose_name="опрос",
            ),
        ),
    ]
