# Generated by Django 4.2.1 on 2023-05-30 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="note",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                validators=[django.core.validators.MinLengthValidator(4)],
                verbose_name="Заметка",
            ),
        ),
    ]
