# Generated by Django 4.2.3 on 2023-07-14 03:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrics", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "key",
                    models.IntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Ключ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип деятельности",
                "verbose_name_plural": "Типы деятельности",
                "ordering": ("key", "id"),
            },
        ),
        migrations.AlterField(
            model_name="burnouttracker",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime,
                verbose_name="Дата/время обновления состояния",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime,
                verbose_name="Дата/время добавления показателей",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="creation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime,
                verbose_name="Дата и время создания опроса",
            ),
        ),
        migrations.AlterField(
            model_name="userlifebalance",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime,
                verbose_name="Дата/время добавления показателей",
            ),
        ),
        migrations.CreateModel(
            name="ActivityTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="Дата"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_trackers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трекер деятельности",
                "verbose_name_plural": "Трекеры деятельности",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="ActivityRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Процент",
                    ),
                ),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_rates",
                        to="metrics.activitytracker",
                        verbose_name="Ежедневный трекер",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.activitytype",
                        verbose_name="Дневное занятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка деятельности",
                "verbose_name_plural": "Оценки деятельности",
                "unique_together": {("type", "tracker")},
            },
        ),
    ]
