# Generated by Django 4.2.1 on 2023-05-30 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_alter_completedsurvey_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="mood",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Настроение",
            ),
        ),
    ]
