# Generated by Django 4.2.1 on 2023-07-18 16:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytype",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
                verbose_name="Цвет",
            ),
        ),
    ]
