# Generated by Django 4.2.1 on 2023-06-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Текст после прохождения опроса"
            ),
        ),
    ]
