# Generated by Django 4.2.1 on 2023-06-28 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burnouttracker",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="burnout_track",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="burnouttracker",
            name="mental_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="burnout_track",
                to="users.mentalstate",
                verbose_name="Состояние",
            ),
        ),
    ]
