# Generated by Django 4.2.1 on 2023-05-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата/время добавления показателей'),
        ),
    ]
