# Generated by Django 4.2.1 on 2023-05-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_condition_date_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
    ]
