# Generated by Django 4.2.1 on 2023-06-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_alter_question_options_question_priority_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="mark",
            field=models.IntegerField(blank=True, null=True, verbose_name="Метка"),
        ),
    ]
