# Generated by Django 4.2.3 on 2023-07-14 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_activitytype_alter_burnouttracker_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityrate",
            name="tracker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_rates",
                to="metrics.activitytracker",
                verbose_name="Трекер",
            ),
        ),
        migrations.AlterField(
            model_name="activityrate",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="metrics.activitytype",
                verbose_name="Тип деятельности",
            ),
        ),
    ]
