# Generated by Django 4.2.1 on 2023-05-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_alter_condition_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="condition",
            options={
                "ordering": ("-id",),
                "verbose_name": "Состояние (сотрудника)",
                "verbose_name_plural": "Состояния",
            },
        ),
    ]
