# Generated by Django 4.2.1 on 2023-06-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_survey_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completedsurvey",
            name="questions",
        ),
        migrations.AlterField(
            model_name="completedsurvey",
            name="results",
            field=models.JSONField(verbose_name="Результаты"),
        ),
    ]
