# Generated by Django 4.2.1 on 2023-06-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0005_alter_variant_for_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="for_type",
        ),
        migrations.AddField(
            model_name="survey",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="metrics.surveytype",
                verbose_name="Тип опроса",
            ),
        ),
    ]
