# Generated by Django 4.2.1 on 2023-05-20 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_alter_survey_description_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
