# Generated by Django 4.2.1 on 2023-06-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0006_alter_userlifebalance_results"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="mark",
        ),
        migrations.AddField(
            model_name="question",
            name="key",
            field=models.IntegerField(blank=True, null=True, verbose_name="Ключ"),
        ),
    ]
