# Generated by Django 4.2.1 on 2023-06-01 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0006_alter_condition_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                default=30,
                validators=[django.core.validators.MaxValueValidator(90)],
                verbose_name="периодичность прохождения опроса",
            ),
        ),
    ]
