# Generated by Django 4.2.1 on 2023-06-13 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0007_remove_question_mark_question_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="max_range",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Максимальный средний порог расчета",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="min_range",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Минимальный средний порог расчета",
            ),
        ),
    ]
