# Generated by Django 4.2.1 on 2023-06-09 11:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0008_alter_completedsurvey_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('num', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Номер')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жизненное направление',
                'verbose_name_plural': 'Жизненное направление',
                'ordering': ('-num',),
            },
        ),
        migrations.CreateModel(
            name='UserLifeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время добавления показателей')),
                ('set_priority', models.BooleanField(default=False, verbose_name='Задать новые приоритеты.')),
                ('set1', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Показатели жизненного направления под номером 1')),
                ('set2', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Показатели жизненного направления под номером 2')),
                ('set3', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Показатели жизненного направления под номером 3')),
                ('set4', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Показатели жизненного направления под номером 4')),
                ('set5', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Показатели жизненного направления под номером 5')),
                ('set6', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Показатели жизненного направления под номером 6')),
                ('set7', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Показатели жизненного направления под номером 7')),
                ('set8', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Показатели жизненного направления под номером 8')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_balance', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Жизненный баланс сотрудника',
                'verbose_name_plural': 'Жизненный баланс сотрудников',
                'ordering': ('-date',),
            },
        ),
    ]
