# Generated by Django 4.2.1 on 2023-06-11 08:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0009_alter_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedsurvey",
            name="next_attempt_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="дата следующей попытки"
            ),
        ),
    ]
