# Generated by Django 4.2.1 on 2023-06-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_lifedirection_userlifebalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifedirection',
            options={'ordering': ('-num',), 'verbose_name': 'Жизненное направление', 'verbose_name_plural': 'Жизненные направления'},
        ),
    ]
