# Generated by Django 4.2.1 on 2023-06-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_alter_lifedirection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifedirection',
            options={'ordering': ('num',), 'verbose_name': 'Жизненное направление', 'verbose_name_plural': 'Жизненные направления'},
        ),
    ]
