# Generated by Django 4.2.1 on 2023-06-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0010_completedsurvey_next_attempt_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedsurvey",
            name="questions",
            field=models.JSONField(verbose_name="Вопросы"),
        ),
        migrations.AlterField(
            model_name="completedsurvey",
            name="summary",
            field=models.JSONField(default=None, null=True, verbose_name="Сводка"),
        ),
    ]
