# Generated by Django 4.2.1 on 2023-06-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_alter_lifedirection_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlifebalance',
            old_name='set1',
            new_name='num1',
        ),
        migrations.RenameField(
            model_name='userlifebalance',
            old_name='set2',
            new_name='num2',
        ),
        migrations.RenameField(
            model_name='userlifebalance',
            old_name='set3',
            new_name='num3',
        ),
        migrations.RenameField(
            model_name='userlifebalance',
            old_name='set4',
            new_name='num4',
        ),
        migrations.RenameField(
            model_name='userlifebalance',
            old_name='set5',
            new_name='num5',
        ),
        migrations.RenameField(
            model_name='userlifebalance',
            old_name='set6',
            new_name='num6',
        ),
        migrations.RenameField(
            model_name='userlifebalance',
            old_name='set7',
            new_name='num7',
        ),
        migrations.RenameField(
            model_name='userlifebalance',
            old_name='set8',
            new_name='num8',
        ),
    ]
