# Generated by Django 4.2.1 on 2023-06-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0012_rename_set1_userlifebalance_num1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlifebalance",
            name="num1",
        ),
        migrations.RemoveField(
            model_name="userlifebalance",
            name="num2",
        ),
        migrations.RemoveField(
            model_name="userlifebalance",
            name="num3",
        ),
        migrations.RemoveField(
            model_name="userlifebalance",
            name="num4",
        ),
        migrations.RemoveField(
            model_name="userlifebalance",
            name="num5",
        ),
        migrations.RemoveField(
            model_name="userlifebalance",
            name="num6",
        ),
        migrations.RemoveField(
            model_name="userlifebalance",
            name="num7",
        ),
        migrations.RemoveField(
            model_name="userlifebalance",
            name="num8",
        ),
        migrations.AddField(
            model_name="userlifebalance",
            name="results",
            field=models.JSONField(default=[], verbose_name="Результаты"),
            preserve_default=False,
        ),
    ]
