# Generated by Django 4.2.1 on 2023-05-21 12:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Тип помощи",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=128,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(8)],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("hr", "HR"), ("chief", "Руководитель")],
                        max_length=10,
                        null=True,
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип помощи",
                "verbose_name_plural": "Типы помощи",
            },
        ),
        migrations.CreateModel(
            name="NeedHelp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        max_length=496,
                        validators=[django.core.validators.MinLengthValidator(4)],
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "viewed",
                    models.BooleanField(default=False, verbose_name="Просмотрено"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время отправки"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_help_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_help_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="socials.helptype",
                        verbose_name="Тип помощи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос помощи",
                "verbose_name_plural": "Запросы помощи",
            },
        ),
    ]
