# Generated by Django 4.2.1 on 2023-06-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        ("socials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="events.entry",
                verbose_name="Запись",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="events.event",
                verbose_name="Событие",
            ),
        ),
    ]
