version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    container_name: em-postgres15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  elasticsearch:
    container_name: em-elasticsearch
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  nginx:
    container_name: em-nginx
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    env_file:
      - .env

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379

volumes:
  elasticsearch:
  postgres:
  static:
  media:
