# Generated by Django 4.2.1 on 2023-05-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mental_state",
            field=models.CharField(
                choices=[
                    ("Нормальное состояние", "Norm"),
                    ("Тревожное", "Hard"),
                    ("В группе риска", "Crit"),
                ],
                default="Нормальное состояние",
                verbose_name="Текущее состояние",
            ),
        ),
    ]
