# Generated by Django 4.2.1 on 2023-07-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_activitytype_color"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hobby",
            name="activity_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="hobbies",
                to="metrics.activitytype",
                verbose_name="Типы активностей",
            ),
        ),
        migrations.AddField(
            model_name="hobby",
            name="life_directions",
            field=models.ManyToManyField(
                blank=True,
                related_name="hobbies",
                to="metrics.lifedirection",
                verbose_name="Жизненные направления",
            ),
        ),
    ]
