# Generated by Django 4.2.1 on 2023-05-14 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitecode",
            options={
                "verbose_name": "Приглашение",
                "verbose_name_plural": "Приглашения",
            },
        ),
        migrations.AddField(
            model_name="invitecode",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AlterField(
            model_name="invitecode",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата отправки инвайта"
            ),
        ),
    ]
