# Generated by Django 4.2.1 on 2023-06-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentalstate",
            options={
                "ordering": ["level"],
                "verbose_name": "Психологическое состояние",
                "verbose_name_plural": "Психологические состояния",
            },
        ),
    ]
