# Generated by Django 4.2.1 on 2023-05-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_invitecode_options_invitecode_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="positions",
                to="users.department",
                verbose_name="Отделы",
            ),
        ),
    ]
