# Generated by Django 4.2.1 on 2023-06-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_user_email_ci_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/thumbnails/",
                verbose_name="Миниатюра аватара/фото",
            ),
        ),
    ]
