# Generated by Django 4.2.1 on 2023-05-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_position_departments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
    ]
