# Generated by Django 4.2.1 on 2023-05-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
    ]
