# Generated by Django 4.2.1 on 2023-06-07 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_mentalstate_alter_user_mental_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentalstate",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(3),
                ],
                verbose_name="Уровень",
            ),
        ),
    ]
