# Generated by Django 4.2.1 on 2023-05-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="departments",
        ),
        migrations.AddField(
            model_name="position",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="users.department",
                verbose_name="Отдел",
            ),
        ),
    ]
