# Generated by Django 4.2.1 on 2023-06-07 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_mentalstate_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentalstate",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Норма"), (2, "Плохо"), (3, "Критический уровень")],
                default=1,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(3),
                ],
                verbose_name="Уровень",
            ),
        ),
    ]
