# Generated by Django 4.2.1 on 2023-06-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_mentalstate_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentalstate",
            name="slug",
        ),
    ]
