# Generated by Django 4.2.1 on 2023-05-15 07:06

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_hobby_options_alter_hobby_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=120,
                validators=[users.validators.validate_first_name],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=120,
                validators=[users.validators.validate_last_name],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                validators=[users.validators.validate_patronymic],
                verbose_name="Отчество",
            ),
        ),
    ]
