# Generated by Django 4.2.1 on 2023-06-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_mentalstate_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mental_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="users.mentalstate",
                verbose_name="Психологическое состояние",
            ),
        ),
    ]
