# Generated by Django 4.2.1 on 2023-06-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_mental_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatar",
            new_name="avatar_full",
        ),
    ]
