# Generated by Django 4.2.1 on 2023-06-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_avatar_user_avatar_full"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatar_full",
            new_name="avatar_img",
        ),
    ]
