# Generated by Django 4.2.1 on 2023-05-18 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_department_description_alter_invitecode_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="department",
        ),
        migrations.RemoveField(
            model_name="position",
            name="description",
        ),
        migrations.AddField(
            model_name="position",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="positions",
                to="users.department",
                verbose_name="Отделы",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="users.department",
                verbose_name="Отдел",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=254,
                null=True,
                validators=[django.core.validators.MinLengthValidator(8)],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                max_length=128,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="hobby",
            name="name",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                max_length=128,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Название должности",
            ),
        ),
    ]
