# Generated by Django 4.2.1 on 2023-06-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_rename_avatar_full_user_avatar_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatar_img",
            new_name="avatar_full",
        ),
    ]
