# Generated by Django 4.2.1 on 2023-05-19 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_position_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                max_length=128,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                max_length=128,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Название должности",
            ),
        ),
    ]
