# Generated by Django 4.2.1 on 2023-05-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_department_name_alter_position_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="chief_position",
            field=models.BooleanField(
                default=False, verbose_name="Руководящая должность"
            ),
        ),
    ]
