# Generated by Django 4.2.1 on 2023-05-19 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_position_chief_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("code", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки кода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сброс пароля",
                "verbose_name_plural": "Спросы паролей",
                "ordering": ["-created"],
            },
        ),
    ]
