# Generated by Django 4.2.1 on 2023-05-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_passwordresetcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordresetcode",
            options={
                "ordering": ["-created"],
                "verbose_name": "Сброс пароля",
                "verbose_name_plural": "Сбросы паролей",
            },
        ),
    ]
