# Generated by Django 4.2.1 on 2023-05-23 13:21

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_department_name_alter_hobby_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    users.validators.validate_email_latin,
                ],
                verbose_name="email",
            ),
        ),
    ]
