name: flake8 tests

on:
  push:
    branches:
      - dev-backend
      - aleksandrusolcev*
  pull_request:
    branches:
      - dev-backend
      - test-backend
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return
    - name: Test with flake8
      run: |
        python -m flake8 backend
